apiVersion: v1
kind: PersistentVolume
metadata:
  name: go-app-pv
spec:
  capacity:
    storage: {{ .Values.persistence.size | default "1Gi" }}
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /mnt/host-app
  persistentVolumeReclaimPolicy: Retain
