replicaCount: 1

image:
  repository: <helm.set.image.repository>
  tag: <helm.set.image.tag>
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80
  targetPort: 2222
  annotations: {}

ingress:
  enabled: true
  className: go-ingress-nginx
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "false"
  hosts:
    - host: go-app-dev.localhost
      paths:
        - path: /
          pathType: Prefix

resources:
  limits:
    cpu: 300m
    memory: 256Mi
  requests:
    cpu: 100m
    memory: 128Mi

autoscaling:
  enabled: false
