replicaCount: 3

image:
  repository: <helm.set.image.repository>
  tag: <helm.set.image.tag>
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80
  targetPort: 2222
  annotations: {}

ingress:
  enabled: true
  className: go-ingress-nginx
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "false"
  hosts:
    - host: go-app.localhost
      paths:
        - path: /
          pathType: Prefix

autoscaling:
  enabled: true
  minReplicas: 3
  maxReplicas: 6
  targetCPUUtilizationPercentage: 75
  behavior:
    scaleUp:
      stabilizationWindowSeconds: 60
      policies:
        - type: Percent
          value: 100
          periodSeconds: 15
    scaleDown:
      stabilizationWindowSeconds: 300
      policies:
        - type: Percent
          value: 50
          periodSeconds: 30

resources:
  limits:
    cpu: 800m
    memory: 512Mi
  requests:
    cpu: 400m
    memory: 256Mi

readinessProbe:
  httpGet:
    path: /healthz
    port: 2222
  initialDelaySeconds: 3
  periodSeconds: 10
  timeoutSeconds: 3
  failureThreshold: 3

livenessProbe:
  httpGet:
    path: /healthz
    port: 2222
  initialDelaySeconds: 10
  periodSeconds: 30
  timeoutSeconds: 3
  failureThreshold: 5

imagePullSecrets:
  - name: myregistrykey
